<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> AttributeError in rsh_target.py
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:qmtest%40codesourcery.com?Subject=Re%3A%20AttributeError%20in%20rsh_target.py&In-Reply-To=%3C003901c2f3f9%2450641de0%24a5452a0a%40jschmittlt%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000270.html">
   <LINK REL="Next"  HREF="000269.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>AttributeError in rsh_target.py</H1>
    <B>John Schmitt</B> 
    <A HREF="mailto:qmtest%40codesourcery.com?Subject=Re%3A%20AttributeError%20in%20rsh_target.py&In-Reply-To=%3C003901c2f3f9%2450641de0%24a5452a0a%40jschmittlt%3E"
       TITLE="AttributeError in rsh_target.py">jschmitt at kealia.com
       </A><BR>
    <I>Thu Mar 27 00:39:23 UTC 2003</I>
    <P><UL>
        <LI>Previous message: <A HREF="000270.html">[qmtest] targets for the local machine
</A></li>
        <LI>Next message: <A HREF="000269.html">[qmtest] AttributeError in rsh_target.py
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#268">[ date ]</a>
              <a href="thread.html#268">[ thread ]</a>
              <a href="subject.html#268">[ subject ]</a>
              <a href="author.html#268">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Any suggestions?

[<A HREF="http://sourcerytools.com/cgi-bin/mailman/listinfo/qmtest">jschmitt at luai</A> jschmitt]$ Exception in thread Thread-1:
Traceback (most recent call last):
  File &quot;//usr/lib/python2.2/threading.py&quot;, line 408, in __bootstrap
    self.run()
  File &quot;/lib/qm/qm/test/execution_thread.py&quot;, line 94, in run
  File &quot;/lib/qm/qm/test/execution_engine.py&quot;, line 130, in Run
  File &quot;/lib/qm/qm/test/classes/process_target.py&quot;, line 140, in Start
  File &quot;/lib/qm/qm/test/classes/rsh_target.py&quot;, line 91, in
_GetInterpreter
AttributeError: 'list' object has no attribute 'split'

I created the target this way:

qmtest create-target -a host=works02 works02target rsh_target.RSHTarget
works02group




</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000270.html">[qmtest] targets for the local machine
</A></li>
	<LI>Next message: <A HREF="000269.html">[qmtest] AttributeError in rsh_target.py
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#268">[ date ]</a>
              <a href="thread.html#268">[ thread ]</a>
              <a href="subject.html#268">[ subject ]</a>
              <a href="author.html#268">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/qmtest">More information about the qmtest
mailing list</a><br>
</body></html>
