<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [c++-pthreads] cancellation points report failure
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20%5Bc%2B%2B-pthreads%5D%20cancellation%20points%20report%20failure&In-Reply-To=%3C1071863363.25325.55.camel%40doubledemon.codesourcery.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000008.html">
   <LINK REL="Next"  HREF="000010.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[c++-pthreads] cancellation points report failure</H1>
    <B>Mark Mitchell</B> 
    <A HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20%5Bc%2B%2B-pthreads%5D%20cancellation%20points%20report%20failure&In-Reply-To=%3C1071863363.25325.55.camel%40doubledemon.codesourcery.com%3E"
       TITLE="[c++-pthreads] cancellation points report failure">mark at codesourcery.com
       </A><BR>
    <I>Fri Dec 19 19:49:23 UTC 2003</I>
    <P><UL>
        <LI>Previous message: <A HREF="000008.html">cancellation points report failure
</A></li>
        <LI>Next message: <A HREF="000010.html">[c++-pthreads] cancellation points report failure
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#9">[ date ]</a>
              <a href="thread.html#9">[ thread ]</a>
              <a href="subject.html#9">[ subject ]</a>
              <a href="author.html#9">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>
&gt;<i> I don't like the idea of ever entirely discarding a cancellation.  If 
</I>&gt;<i> a cancellation exception is thrown, caught, and discarded, I would like
</I>&gt;<i> to see it surface again at the next opportunity.  I think that means 
</I>&gt;<i> that, e.g., I/O operations might be allowed in exception-handling code
</I>&gt;<i> being run during the cancellation unwind, but if one of those handlers 
</I>&gt;<i> were to swallow the exception, the next I/O operation would fail or
</I>&gt;<i> throw another cancellation.  The idea is not to let the thread get
</I>&gt;<i> much further without finding cause to bubble up toward the top-level
</I>&gt;<i> caller that knows it's in a thread, and can die gracefully.
</I>
I think that is a reasonable idea.  

I would much prefer that to (say) implicitly rethrowing cancellation
exceptions. 

-- 
Mark Mitchell &lt;<A HREF="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">mark at codesourcery.com</A>&gt;
CodeSourcery, LLC


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000008.html">cancellation points report failure
</A></li>
	<LI>Next message: <A HREF="000010.html">[c++-pthreads] cancellation points report failure
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#9">[ date ]</a>
              <a href="thread.html#9">[ thread ]</a>
              <a href="subject.html#9">[ subject ]</a>
              <a href="author.html#9">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">More information about the c++-pthreads
mailing list</a><br>
</body></html>
