<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> Does the cancelation exception have a name?
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20Does%20the%20cancelation%20exception%20have%20a%20name%3F&In-Reply-To=%3C454D055E.2896C0C%40web.de%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000598.html">
   <LINK REL="Next"  HREF="000600.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>Does the cancelation exception have a name?</H1>
    <B>Alexander Terekhov</B> 
    <A HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20Does%20the%20cancelation%20exception%20have%20a%20name%3F&In-Reply-To=%3C454D055E.2896C0C%40web.de%3E"
       TITLE="Does the cancelation exception have a name?">terekhov at web.de
       </A><BR>
    <I>Sat Nov  4 21:25:50 UTC 2006</I>
    <P><UL>
        <LI>Previous message: <A HREF="000598.html">Does the cancelation exception have a name?
</A></li>
        <LI>Next message: <A HREF="000600.html">[c++-pthreads]  Re: Does the cancelation exception have a name?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#599">[ date ]</a>
              <a href="thread.html#599">[ thread ]</a>
              <a href="subject.html#599">[ subject ]</a>
              <a href="author.html#599">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>#define PTHREAD_CANCELED std::thread_canceled()

struct thread_canceled {
  operator void * () { return &unique; }
  static thread_canceled unique;
};

extern &quot;C&quot; void pthread_exit(void * ptr)
	throw(std::thread_termination_request) {
  ptr == PTHREAD_CANCELED ? std::thread_cancel() :
                            std::thread_exit(ptr);

} 
template&lt;typename T&gt;
void thread_exit(T value) {
  assert(std::thread_self().can_exit_with&lt;T&gt;());
  throw thread_exit_value(value);
}

template&lt;&gt;
void thread_exit(std::thread_canceled) {
  thread_cancel();
}

void thread_cancel() {
  throw std::thread_cancel_request();
} 

regards,
alexender.


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000598.html">Does the cancelation exception have a name?
</A></li>
	<LI>Next message: <A HREF="000600.html">[c++-pthreads]  Re: Does the cancelation exception have a name?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#599">[ date ]</a>
              <a href="thread.html#599">[ thread ]</a>
              <a href="subject.html#599">[ subject ]</a>
              <a href="author.html#599">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">More information about the c++-pthreads
mailing list</a><br>
</body></html>
