<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> pthread_cancel and EH: let's try this again
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20pthread_cancel%20and%20EH%3A%20let%27s%20try%20this%20again&In-Reply-To=%3C42D91034.555BA7F2%40web.de%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000397.html">
   <LINK REL="Next"  HREF="000501.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>pthread_cancel and EH: let's try this again</H1>
    <B>Alexander Terekhov</B> 
    <A HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20pthread_cancel%20and%20EH%3A%20let%27s%20try%20this%20again&In-Reply-To=%3C42D91034.555BA7F2%40web.de%3E"
       TITLE="pthread_cancel and EH: let's try this again">terekhov at web.de
       </A><BR>
    <I>Sat Jul 16 13:48:36 UTC 2005</I>
    <P><UL>
        <LI>Previous message: <A HREF="000397.html">[c++-pthreads]  Re: pthread_cancel and EH: let's try this again
</A></li>
        <LI>Next message: <A HREF="000501.html">[c++-pthreads]  Re: pthread_cancel and EH: let's try this again
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#398">[ date ]</a>
              <a href="thread.html#398">[ thread ]</a>
              <a href="subject.html#398">[ subject ]</a>
              <a href="author.html#398">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>
Dave Butenhof wrote:
[...]
&gt;<i> the cancel &amp; exit EXCEPTIONS have names. They can be caught AND
</I>&gt;<i> FINALIZED (legally not re-thrown) BY NAME
</I>
Yes.

&gt;<i>  (only). If caught anonymously, they must be re-thrown. 
</I>
This &quot;compromise&quot; makes no sense.

  void test_cancel() throw(thread_cancel_request) {
    pthread_testcancel();
  }

This

  try {
    testcancel(); // can throw only thread_cancel_request
  }
  catch(thread_cancel_request const &amp;) { }

is oughta be the same as 

  try {
    testcancel(); // can throw only thread_cancel_request
  }
  catch(...) { }

Uhmm, unless you seriously want the above be written as

  try {
    testcancel(); // can throw only thread_cancel_request
  }
  catch(...) { 
    stop_stupid_abort();
  }

  void stop_stupid_abort() {
    try { throw; } catch(thread_cancel_request const &amp;) { }
  }

regards,
alexander.


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000397.html">[c++-pthreads]  Re: pthread_cancel and EH: let's try this again
</A></li>
	<LI>Next message: <A HREF="000501.html">[c++-pthreads]  Re: pthread_cancel and EH: let's try this again
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#398">[ date ]</a>
              <a href="thread.html#398">[ thread ]</a>
              <a href="subject.html#398">[ subject ]</a>
              <a href="author.html#398">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">More information about the c++-pthreads
mailing list</a><br>
</body></html>
