<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> pthread_cancel and EH: let's try this again
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20pthread_cancel%20and%20EH%3A%20let%27s%20try%20this%20again&In-Reply-To=%3C42DF8DFB.C1578B88%40web.de%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000482.html">
   <LINK REL="Next"  HREF="000500.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>pthread_cancel and EH: let's try this again</H1>
    <B>Alexander Terekhov</B> 
    <A HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20pthread_cancel%20and%20EH%3A%20let%27s%20try%20this%20again&In-Reply-To=%3C42DF8DFB.C1578B88%40web.de%3E"
       TITLE="pthread_cancel and EH: let's try this again">terekhov at web.de
       </A><BR>
    <I>Thu Jul 21 11:58:51 UTC 2005</I>
    <P><UL>
        <LI>Previous message: <A HREF="000482.html">[c++-pthreads]  Re: pthread_cancel and EH: let's try this again
</A></li>
        <LI>Next message: <A HREF="000500.html">[c++-pthreads]  Re: pthread_cancel and EH: let's try this again
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#484">[ date ]</a>
              <a href="thread.html#484">[ thread ]</a>
              <a href="subject.html#484">[ subject ]</a>
              <a href="author.html#484">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>
Peter Dimov wrote:
&gt;<i> 
</I>&gt;<i> Alexander Terekhov wrote:
</I>&gt;<i> &gt; Peter Dimov wrote:
</I>&gt;<i> &gt;&gt;
</I>&gt;<i> &gt;&gt; The stack unwinding doesn't end when the catch block is entered.
</I>&gt;<i> &gt;&gt; That's when the exception is &quot;caught&quot; - uncaught_exception() starts
</I>&gt;<i> &gt;&gt; returning true - but it's not until the catch block ends when the
</I>&gt;<i> &gt;&gt; exception is considered &quot;finished&quot;.
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; Really? Read the definition.
</I>&gt;<i> 
</I>&gt;<i> OK, let's not talk about stack unwinding to avoid the terminology trap. The
</I>&gt;<i> point is that under one of the models being discussed, cancel delivery is
</I>&gt;<i> suppressed until the exception is finished.
</I>
I don't like that. It's way too inhibitive. 

regards,
alexander.


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000482.html">[c++-pthreads]  Re: pthread_cancel and EH: let's try this again
</A></li>
	<LI>Next message: <A HREF="000500.html">[c++-pthreads]  Re: pthread_cancel and EH: let's try this again
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#484">[ date ]</a>
              <a href="thread.html#484">[ thread ]</a>
              <a href="subject.html#484">[ subject ]</a>
              <a href="author.html#484">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">More information about the c++-pthreads
mailing list</a><br>
</body></html>
