From minal.lamture at celunite.com  Fri Aug  3 11:56:46 2007
From: minal.lamture at celunite.com (Minal Lamture)
Date: Fri, 03 Aug 2007 17:26:46 +0530
Subject: Regarding test cases which run in loop
Message-ID: <1186142206.17010.12.camel@minal-desktop>

Hello all,

I want to use QMTest for running test application wchich is in
continuous loop.
Problem is it never exits. It checks for signals continuously. And unitl
and unless it quits QMTest will not show the result.

So is there any way to check this kind of applications which run in
loop?

--
Minal



From stefan at codesourcery.com  Fri Aug  3 15:16:27 2007
From: stefan at codesourcery.com (Stefan Seefeld)
Date: Fri, 03 Aug 2007 11:16:27 -0400
Subject: [qmtest] Regarding test cases which run in loop
In-Reply-To: <1186142206.17010.12.camel@minal-desktop>
References: <1186142206.17010.12.camel@minal-desktop>
Message-ID: <46B346CB.7090809@codesourcery.com>

Minal Lamture wrote:
> Hello all,
> 
> I want to use QMTest for running test application wchich is in
> continuous loop.
> Problem is it never exits. It checks for signals continuously. And unitl
> and unless it quits QMTest will not show the result.
> 
> So is there any way to check this kind of applications which run in
> loop?

How do you define 'test' in this context ? Conceptually, it sounds like
a server, with tests being requests together with expected answers. So
may be you could set up your tests in a way that such a server gets started
by a resource instance, and tests then issue requests to that and compare the
results with expected values ? (But even then, there is no continuous loop.
A test has a finite set of tasks to run before it determines whether it passed
or failed, and a test suite has a finite set of tests...)

I would need more context to be able to make more detailed suggestions.

Regards,
		Stefan


-- 
Stefan Seefeld
CodeSourcery
stefan at codesourcery.com
(650) 331-3385 x718


From mark at codesourcery.com  Mon Aug  6 18:36:15 2007
From: mark at codesourcery.com (Mark Mitchell)
Date: Mon, 06 Aug 2007 11:36:15 -0700
Subject: [qmtest] Regarding common problem
In-Reply-To: <72DE65ED2FEE5B438EA7EE30DE5F2D221C66A4@AAEXCVS06.ES.AD.ADP.COM>
References: <72DE65ED2FEE5B438EA7EE30DE5F2D221C66A4@AAEXCVS06.ES.AD.ADP.COM>
Message-ID: <46B76A1F.8050706@codesourcery.com>

Bommisetty, Satish wrote:

>          Please provide those Qmtest extensions which supports windows
> GUI. 

QMTest does not have test classes for Windows GUI testing.  You would
have to write all of that code yourself.

Thanks,

-- 
Mark Mitchell
CodeSourcery
mark at codesourcery.com
(650) 331-3385 x713


From melkin at qualcomm.com  Wed Aug  8 20:27:51 2007
From: melkin at qualcomm.com (Mark Elkin)
Date: Wed, 08 Aug 2007 13:27:51 -0700
Subject: qm-2.3 Installation Check error
Message-ID: <7.0.1.0.2.20070808131720.052ee070@qualcomm.com>

I'm installing qmtest on a Linux system after downloading the 
qm-2.3.tar.gz source.  The install seems to go fine.  But when I run 
the check, I get an error.  (The terminal session is below).  I've 
looked through the maillist archives back to 1/1/2006 and don't see 
answer.  Do you have any suggestions how I can fix it?

TIA,
Mark


[root at axa2 qm-2.3]# cat /proc/version
Linux version 2.6.22.1 (maxk at axa) (gcc version 4.1.2 20070502 (Red 
Hat 4.1.2-12)) #12 SMP PREEMPT Wed Jul 11 21:53:30 PDT 2007

[root at axa2 qm-2.3]# python
Python 2.5 (r25:51908, Apr 10 2007, 10:27:40)
[GCC 4.1.2 20070403 (Red Hat 4.1.2-8)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
 >>> quit()

[root at axa2 qm-2.3]# python setup.py check
running check
running build
running build_py
copying qm/test/qmtest.py -> build/lib.linux-x86_64-2.5/qm/test
running build_ext
running build_scripts
copying and adjusting qm/test/qmtest.py -> build/scripts-2.5
/home/mark/qm-2.3/build/scripts-2.5/qmtest -D tests run -c 
qmtest_path=/home/mark/qm-2.3/build/scripts-2.5/qmtest
Traceback (most recent call last):
   File "/home/mark/qm-2.3/build/scripts-2.5/qmtest", line 130, in <module>
     import qm.test.cmdline
   File 
"/home/mark/qm-2.3/build/lib.linux-x86_64-2.5/qm/test/cmdline.py", 
line 20, in <module>
     import base
   File 
"/home/mark/qm-2.3/build/lib.linux-x86_64-2.5/qm/test/base.py", line 
389, in <module>
     import qm.test.database
   File 
"/home/mark/qm-2.3/build/lib.linux-x86_64-2.5/qm/test/database.py", 
line 23, in <module>
     import qm.extension
   File 
"/home/mark/qm-2.3/build/lib.linux-x86_64-2.5/qm/extension.py", line 
20, in <module>
     from qm.fields import Field
   File "/home/mark/qm-2.3/build/lib.linux-x86_64-2.5/qm/fields.py", 
line 58, in <module>
     import web
   File "/home/mark/qm-2.3/build/lib.linux-x86_64-2.5/qm/web.py", 
line 48, in <module>
     import qm.external.DocumentTemplate as DocumentTemplate
   File 
"/home/mark/qm-2.3/build/lib.linux-x86_64-2.5/qm/external/DocumentTemplate/__init__.py", 
line 96, in <module>
     from DocumentTemplate import String, File, HTML, HTMLDefault, HTMLFile
   File 
"/home/mark/qm-2.3/build/lib.linux-x86_64-2.5/qm/external/DocumentTemplate/DocumentTemplate.py", 
line 201, in <module>
     from DT_String import String, File
   File 
"/home/mark/qm-2.3/build/lib.linux-x86_64-2.5/qm/external/DocumentTemplate/DT_String.py", 
line 88, in <module>
     import regex, ts_regex
ImportError: No module named regex
error: command '/home/mark/qm-2.3/build/scripts-2.5/qmtest' failed 
with exit status 1



From mark.jones73 at gmail.com  Wed Aug  8 21:34:49 2007
From: mark.jones73 at gmail.com (Mark Jones)
Date: Wed, 8 Aug 2007 22:34:49 +0100
Subject: [qmtest] qm-2.3 Installation Check error
In-Reply-To: <7.0.1.0.2.20070808131720.052ee070@qualcomm.com>
References: <7.0.1.0.2.20070808131720.052ee070@qualcomm.com>
Message-ID: <46ba36fc.2275420a.2134.4b11@mx.google.com>

Mark,

I'm sure you'll get a few responses to this but none so far so...

The problem is that the python version you have is 2.5 which had the regex
modules removed in it. The last version they were included was V2.4. These
have been replaced by the 're' module but having looked at qmtest it isn't a
simple change to move it across to the 're' module from the 'regex' module.
Regex has been deprecated for a while but was finally removed in python
V2.4.

So.. to solve this you will have install a different python library based on
python2.4.x

I fell over this on first install too

Hope this helps

Mark

-----Original Message-----
From: Mark Elkin [mailto:melkin at qualcomm.com] 
Sent: 08 August 2007 21:28
To: qmtest at codesourcery.com
Cc: melkin at qualcomm.com
Subject: [qmtest] qm-2.3 Installation Check error

I'm installing qmtest on a Linux system after downloading the 
qm-2.3.tar.gz source.  The install seems to go fine.  But when I run 
the check, I get an error.  (The terminal session is below).  I've 
looked through the maillist archives back to 1/1/2006 and don't see 
answer.  Do you have any suggestions how I can fix it?

TIA,
Mark




From stefan at codesourcery.com  Thu Aug  9 07:34:25 2007
From: stefan at codesourcery.com (Stefan Seefeld)
Date: Thu, 09 Aug 2007 03:34:25 -0400
Subject: [qmtest] qm-2.3 Installation Check error
In-Reply-To: <46ba36fc.2275420a.2134.4b11@mx.google.com>
References: <7.0.1.0.2.20070808131720.052ee070@qualcomm.com> <46ba36fc.2275420a.2134.4b11@mx.google.com>
Message-ID: <46BAC381.70208@codesourcery.com>

Mark Jones wrote:
> Mark,
> 
> I'm sure you'll get a few responses to this but none so far so...
> 
> The problem is that the python version you have is 2.5 which had the regex
> modules removed in it. The last version they were included was V2.4. These
> have been replaced by the 're' module but having looked at qmtest it isn't a
> simple change to move it across to the 're' module from the 'regex' module.
> Regex has been deprecated for a while but was finally removed in python
> V2.4.

You are exactly right.
We have removed QMTest's dependency on that module in the repository, and
hope to get a new release out in not too distant a future.

Thanks,
		Stefan

-- 
Stefan Seefeld
CodeSourcery
stefan at codesourcery.com
(650) 331-3385 x718


From root at ianlawrence.info  Mon Aug 13 22:52:10 2007
From: root at ianlawrence.info (Ian Lawrence)
Date: Mon, 13 Aug 2007 18:52:10 -0400 (AMT)
Subject: A python setup.py check error on threads
Message-ID: <58569.192.100.104.17.1187045530.squirrel@mail2.webfaction.com>

Hi,
I followed this process and got an error. Any hints would be great!!

I am on Ubuntu Feisty
Python 2.5.1 (r251:54863, May  2 2007, 16:56:35)
[GCC 4.1.2 (Ubuntu 4.1.2-0ubuntu4)] on linux2

I did:
svn co svn://source.codesourcery.com/qmtest/trunk qmtest
python setup.py build
python setup.py check --thread

gives me the following results:

 Setup xmldb.test.classes.tempdir1             : PASS

  xmldb.test.classes.tempdir1                   : PASS

  Cleanup xmldb.test.classes.tempdir1           : PASS

  Cleanup xmldb.signals_unblocked_tmpdir        : PASS

--- TESTS THAT DID NOT PASS
--------------------------------------------------

  regress.env_context1                          : FAIL
    Child process exited unsuccessfully

  regress.xml1                                  : FAIL
    Child process exited unsuccessfully

  regress.xml2                                  : FAIL
    Child process exited unsuccessfully

  xmldb.common.parser_dup_command_long          : FAIL
    The test code raised an exception that isn't an exception object
    instance. The type of the exception was ''.

  xmldb.common.parser_dup_command_short         : FAIL
    The test code raised an exception that isn't an exception object
    instance. The type of the exception was ''.

  xmldb.common.parser_no_long                   : FAIL
    The test code raised an exception that isn't an exception object
    instance. The type of the exception was ''.

  xmldb.common.parser_two_char_short            : FAIL
    The test code raised an exception that isn't an exception object
    instance. The type of the exception was ''.

  xmldb.signals_unblocked                       : ERROR
    An exception occurred.

  xmldb.test.classes.scripttest1                : ERROR
    An exception occurred.

  xmldb.test.classes.scripttest_closes_stdin    : ERROR
    An exception occurred.


--- STATISTICS
---------------------------------------------------------------

      47        tests total
       3 (  6%) tests ERROR
       7 ( 15%) tests FAIL
      37 ( 79%) tests PASS

an example of the actual error generated is (all tests fail on the same
line):
  xmldb.test.classes.scripttest_closes_stdin    : ERROR
    An exception occurred.

    qmtest.end_time:
      2007-08-13T22:38:30Z

    qmtest.exception:

      <type 'exceptions.OSError'>: [Errno 3] No such process


    qmtest.start_time:
      2007-08-13T22:38:30Z

    qmtest.target:
      thread

    qmtest.traceback:

        File
"/home/ian/Dev/Indt/Testing/qmtest-upstream/build/lib.linux-i686-2.5/qm/test/target.py",
line 227, in RunTest
          descriptor.Run(context, result)

        File
"/home/ian/Dev/Indt/Testing/qmtest-upstream/build/lib.linux-i686-2.5/qm/test/database.py",
line 272, in Run
          self._Execute(context, result, "Run")

        File
"/home/ian/Dev/Indt/Testing/qmtest-upstream/build/lib.linux-i686-2.5/qm/test/database.py",
line 191, in _Execute
          methobj(context, result)

        File
"/home/ian/Dev/Indt/Testing/qmtest-upstream/qm/test/classes/command.py",
line 456, in Run
          self.RunProgram(arguments[0], arguments, context, result)

        File
"/home/ian/Dev/Indt/Testing/qmtest-upstream/qm/test/classes/command.py",
line 221, in RunProgram
          status = e.Run(arguments, environment, path = program)

        File
"/home/ian/Dev/Indt/Testing/qmtest-upstream/build/lib.linux-i686-2.5/qm/executable.py",
line 564, in Run
          path)

        File
"/home/ian/Dev/Indt/Testing/qmtest-upstream/build/lib.linux-i686-2.5/qm/executable.py",
line 270, in Run
          child = self.Spawn(arguments, environment, dir, path,
exception_pipe)

        File
"/home/ian/Dev/Indt/Testing/qmtest-upstream/build/lib.linux-i686-2.5/qm/executable.py",
line 222, in Spawn
          self._HandleChild()

        File
"/home/ian/Dev/Indt/Testing/qmtest-upstream/build/lib.linux-i686-2.5/qm/executable.py",
line 732, in _HandleChild
          super(RedirectedExecutable, self)._HandleChild()

        File
"/home/ian/Dev/Indt/Testing/qmtest-upstream/build/lib.linux-i686-2.5/qm/executable.py",
line 508, in _HandleChild
          os.setpgid(self.__monitor_pid, child_pid)

thanks for your help
[]'s
Ian


-- 

http://ianlawrence.info


From stefan at codesourcery.com  Wed Aug 22 14:24:37 2007
From: stefan at codesourcery.com (Stefan Seefeld)
Date: Wed, 22 Aug 2007 10:24:37 -0400
Subject: [Fwd: [support] New feature in QMTest]
In-Reply-To: <469AFB95.2020905@codesourcery.com>
References: <469AFB95.2020905@codesourcery.com>
Message-ID: <46CC4725.4020001@codesourcery.com>

Kristoffer,

sorry for getting back to you about this feature request this late.

I think the extension you propose is a great idea. Being able to
'mount' databases not located directly in a subdirectory seems
very convenient.

However, there are some minor things that need to be considered:

* Each mounted database needs to be referred to by an id that
  has to obey some constraints. In general, using the file system path
  leading to the database's location may not work.
  But using a dictionary instead of a list should work.

* I don't see any reason to modify anything but the MountDatabase
  to add this feature. In particular, the Database base class
  shouldn't be affected.

* For simplicity's sake, I'd suggest to drop the 'type' parameter.
  I imagine this simple rule:
  - if a dictionary of sub databases is present, only that is used
  - if none is present, the local subdirectories are scanned.
  - if you really want both, add entries for the local subdirectories
    into the dictionary

Does this make sense to you ?

Implementation detail: we don't yet have a way to pass a dictionary
on the command line, so setting up a mount database the way you suggest
wouldn't work via 'qmtest create_db'. Until this is implemented, you
would have to modify the QMTest/configuration file directly.

Thanks,
		Stefan


-- 
Stefan Seefeld
CodeSourcery
stefan at codesourcery.com
(650) 331-3385 x718


