<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [c++-pthreads] Re: thread-safety definition
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20%5Bc%2B%2B-pthreads%5D%20Re%3A%20thread-safety%20definition&In-Reply-To=%3C20040110151040.GB13609%40diablo.name%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000190.html">
   <LINK REL="Next"  HREF="000191.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[c++-pthreads] Re: thread-safety definition</H1>
    <B>Ted Baker</B> 
    <A HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20%5Bc%2B%2B-pthreads%5D%20Re%3A%20thread-safety%20definition&In-Reply-To=%3C20040110151040.GB13609%40diablo.name%3E"
       TITLE="[c++-pthreads] Re: thread-safety definition">baker at cs.fsu.edu
       </A><BR>
    <I>Sat Jan 10 15:10:40 UTC 2004</I>
    <P><UL>
        <LI>Previous message: <A HREF="000190.html">[c++-pthreads] Re: thread-safety definition
</A></li>
        <LI>Next message: <A HREF="000191.html">[c++-pthreads] Re: thread-safety definition
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#189">[ date ]</a>
              <a href="thread.html#189">[ thread ]</a>
              <a href="subject.html#189">[ subject ]</a>
              <a href="author.html#189">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>&gt;<i> &gt;I don't really see what you think is complicated about this.  In
</I>&gt;<i> &gt;Jason's model cancellation gets reasserted as soon as a caught
</I>&gt;<i> &gt;cancellation exception is destroyed by falling off the end of the
</I>&gt;<i> &gt;catch block without rethrowing.
</I>&gt;<i> 
</I>&gt;<i> What if, at that point, the thread has disabled cancellation?
</I>
First, if the thread had disabled cancellation before the the
cancellation exception was raised, you could not get to this
point.  Therefore, you are only asking about the case where a
thread disables cancellation in a cleanup routine or destructor
and does not reenable it.  In this case you still want to
&quot;reassert&quot; the cancellation at the next point control leaves
a handler/catch block without rethrowing.

--Ted

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000190.html">[c++-pthreads] Re: thread-safety definition
</A></li>
	<LI>Next message: <A HREF="000191.html">[c++-pthreads] Re: thread-safety definition
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#189">[ date ]</a>
              <a href="thread.html#189">[ thread ]</a>
              <a href="subject.html#189">[ subject ]</a>
              <a href="author.html#189">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">More information about the c++-pthreads
mailing list</a><br>
</body></html>
