<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [c++-pthreads] Re: thread-safety definition
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20%5Bc%2B%2B-pthreads%5D%20Re%3A%20thread-safety%20definition&In-Reply-To=%3C3FFE43BB.6040809%40bogo.xs4all.nl%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000162.html">
   <LINK REL="Next"  HREF="000179.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[c++-pthreads] Re: thread-safety definition</H1>
    <B>Wil Evers</B> 
    <A HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20%5Bc%2B%2B-pthreads%5D%20Re%3A%20thread-safety%20definition&In-Reply-To=%3C3FFE43BB.6040809%40bogo.xs4all.nl%3E"
       TITLE="[c++-pthreads] Re: thread-safety definition">wil at bogo.xs4all.nl
       </A><BR>
    <I>Fri Jan  9 06:01:31 UTC 2004</I>
    <P><UL>
        <LI>Previous message: <A HREF="000162.html">[c++-pthreads] Re: thread-safety definition
</A></li>
        <LI>Next message: <A HREF="000179.html">[c++-pthreads] Re: thread-safety definition
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#178">[ date ]</a>
              <a href="thread.html#178">[ thread ]</a>
              <a href="subject.html#178">[ subject ]</a>
              <a href="author.html#178">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Dave Butenhof wrote:

&gt;<i> Wil Evers wrote:
</I>&gt;<i> 
</I>&gt;&gt;<i> Dave Butenhof wrote:
</I>&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> If cancel is implemented completely as a &quot;full stature&quot; C++ 
</I>&gt;&gt;&gt;<i> exception, and none of the &quot;exception safe&quot; code does anything silly 
</I>&gt;&gt;&gt;<i> like &quot;catch(...)&quot; without a re-throw, then, yes, it's likely to be 
</I>&gt;&gt;&gt;<i> reasonably cancel-safe. 
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> A catch(...) without a re-throw isn't necessarily a silly thing to do, 
</I>&gt;&gt;<i> especially in a destructor.  Sometimes, the only alternative is to 
</I>&gt;&gt;<i> risk a call to terminate().
</I>&gt;<i> 
</I>&gt;<i> But it still breaks cancellation. Again, ignoring cancel entirely may be 
</I>&gt;<i> &quot;cancel safe&quot; in some trivial sense, but it's not useful or reasonable 
</I>&gt;<i> under nearly all circumstances.
</I>
I'm not suggesting that catching a cancellation request and not 
rethrowing it is a good thing.  I'm trying to point out that - sometimes 
- the C++ language rules leave with me no other choice.  A second 
exception escaping from a destructor called while unwinding the stack 
because of some earlier exception will result in program termination.

If catching (and not rethrowing) this second exception breaks the 
cancellation machinery, then it is the cancellation machinery - and not 
the program in question - that is broken.  In other words: we need a way 
to prevent this scenario.

- Wil


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000162.html">[c++-pthreads] Re: thread-safety definition
</A></li>
	<LI>Next message: <A HREF="000179.html">[c++-pthreads] Re: thread-safety definition
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#178">[ date ]</a>
              <a href="thread.html#178">[ thread ]</a>
              <a href="subject.html#178">[ subject ]</a>
              <a href="author.html#178">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">More information about the c++-pthreads
mailing list</a><br>
</body></html>
