<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [c++-pthreads]  Re: FW: RE: Re: I'm Lost
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20%5Bc%2B%2B-pthreads%5D%20%20Re%3A%20FW%3A%20RE%3A%20Re%3A%20I%27m%20Lost&In-Reply-To=%3Cuek1fdy1d.fsf%40boost-consulting.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000536.html">
   <LINK REL="Next"  HREF="000538.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[c++-pthreads]  Re: FW: RE: Re: I'm Lost</H1>
    <B>David Abrahams</B> 
    <A HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20%5Bc%2B%2B-pthreads%5D%20%20Re%3A%20FW%3A%20RE%3A%20Re%3A%20I%27m%20Lost&In-Reply-To=%3Cuek1fdy1d.fsf%40boost-consulting.com%3E"
       TITLE="[c++-pthreads]  Re: FW: RE: Re: I'm Lost">dave at boost-consulting.com
       </A><BR>
    <I>Mon Mar  6 22:10:54 UTC 2006</I>
    <P><UL>
        <LI>Previous message: <A HREF="000536.html">[c++-pthreads]  Re: FW: RE: Re: I'm Lost
</A></li>
        <LI>Next message: <A HREF="000538.html">[c++-pthreads]  Re: FW: RE: Re: I'm Lost
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#537">[ date ]</a>
              <a href="thread.html#537">[ thread ]</a>
              <a href="subject.html#537">[ subject ]</a>
              <a href="author.html#537">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Dave Butenhof &lt;<A HREF="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">david.butenhof at hp.com</A>&gt; writes:

&gt;&gt;&gt;<i> This has been THE most contentious issue in every C++/threads
</I>&gt;&gt;&gt;<i> discussion I've encountered since the beginning of (pthread) time.
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> My preference has always been that cancellation is an
</I>&gt;&gt;&gt;<i> exception. Period. In our initial CMA architecture, and in our
</I>&gt;&gt;&gt;<i> exception mapping of cancellation/thread-exit onto C language
</I>&gt;&gt;&gt;<i> exceptions in Tru64 UNIX and OpenVMS, it's possible and reasonable
</I>&gt;&gt;&gt;<i> to finalize propagation of a cancel/exit exception. That was
</I>&gt;&gt;&gt;<i> critical for DCE, for example, so that it could trap cancellation
</I>&gt;&gt;&gt;<i> of an RPC server thread, bring the thread back into the server's
</I>&gt;&gt;&gt;<i> work pool, and propagate the exception across the wire to the
</I>&gt;&gt;&gt;<i> client.
</I>&gt;&gt;&gt;<i>     
</I>&gt;&gt;<i> That sounds highly analogous to my case with Python.
</I>&gt;&gt;<i>   
</I>&gt;<i> Sure; and there are other examples. I've just found that the &quot;inverted 
</I>&gt;<i> call stack&quot; of this sort of server setup seems to make sense to a lot of 
</I>&gt;<i> people.
</I>
Okay.  So there's a moderate-sized class of applications that need to
do this.

&gt;&gt;&gt;<i> To finalize a cancel/exit under almost any normal circumstance is
</I>&gt;&gt;&gt;<i> simply an application error.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> The key word being &quot;almost.&quot;  In some situations, like those we've
</I>&gt;&gt;<i> both cited, it's absolutely necessary, to even get cancellation to
</I>&gt;&gt;<i> work.
</I>&gt;&gt;<i>   
</I>&gt;<i> Absolutely. There was a strong sub-faction in POSIX that can be
</I>&gt;<i> loosely characterized as &quot;academics&quot; who were determined to try to
</I>&gt;<i> prevent constructs that might be misused. 
</I>
You mean, like, computers?

&gt;<i> It's why the realtime people didn't get pthread_abort() to force
</I>&gt;<i> termination without cleanup, why you can't suspend a thread, or
</I>&gt;<i> &quot;force unlock&quot; a mutex that might have been abandoned, and so
</I>&gt;<i> forth. 
</I>
Oh, too bad.

&gt;<i> If cancellation can't be finalized, nobody can accidentally
</I>&gt;<i> finalize it; and that's great if you don't trust anyone to know when
</I>&gt;<i> it SHOULD be finalized. I started out as something of an &quot;academic&quot;
</I>&gt;<i> in this sense and evolved into a pramatist... if someone thinks they
</I>&gt;<i> need it, and they're right, don't keep them from doing it.  And if
</I>&gt;<i> they're WRONG, it's their problem, not yours. ;-) Portable Java GC
</I>&gt;<i> would have been a lot easier had POSIX included suspend/resume; and
</I>&gt;<i> does it really matter that nearly anyone else who used it would be
</I>&gt;<i> breaking their application? Well, it all depends on your point of
</I>&gt;<i> view...
</I>
I don't know about that suspend/resume, but I don't think legitimate
cases where finalization is needed are nearly so rare as you describe
cases where suspend/resume is needed to be.

&gt;&gt;<i> A ctor that does catch(...) without rethrow is almost always badly
</I>&gt;&gt;<i> designed at best.  There was unfortunate advice going around for many
</I>&gt;&gt;<i> years that you shouldn't throw from ctors, but that's exactly wrong:
</I>&gt;&gt;<i> ctors that throw allow the establishment of strong invariants, and
</I>&gt;&gt;<i> programming without them is much harder.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> On the other hand, stopping exceptions in dtors is absolutely the
</I>&gt;&gt;<i> right thing to do.
</I>&gt;&gt;<i>   
</I>&gt;<i> Yes, I may have said that backwards. As I've said before, although I use 
</I>&gt;<i> C++, it's not a &quot;native language&quot; for me, and a lot of this is based on 
</I>&gt;<i> opinions others have strongly stated 
</I>
It wouldn't surprise me a bit if others had strongly stated ctors
shouldn't throw.  It used to be the advice in Stroustrup's books.

&gt;<i> rather than my own knowledge or experience. Another reason,
</I>&gt;<i> incidentally, for not trying to come down too hard on one side or
</I>&gt;<i> the other where language concerns might trump &quot;threading&quot; concerns.
</I>&gt;<i>
</I>&gt;&gt;&gt;<i> and they have some legitimate concerns about common C++ language
</I>&gt;&gt;&gt;<i> patterns that might pretty much prevent a cancel from ever doing
</I>&gt;&gt;&gt;<i> what a cancel should do.
</I>&gt;&gt;&gt;<i>     
</I>&gt;&gt;<i> Really, legitimate concerns? I can't think of any recommended
</I>&gt;&gt;<i> patterns that would act that way.
</I>&gt;&gt;<i>   
</I>&gt;<i> Hmm. OK. That's interesting. Well, you're the C++ expert here. ;-)
</I>
None other than, &quot;prevent exceptions from leaking across language
boundaries.&quot;  But if you don't do that, your program is broken anyway.

&gt;&gt;<i> You don't find the idea that exception-safe code implies cancel-safe
</I>&gt;&gt;<i> code technically compelling?  I don't think that's an emotional issue.
</I>&gt;&gt;<i>   
</I>&gt;<i> Well, yes, I do, 
</I>
find it technically compelling, or think it's an emotional issue?

&gt;<i> because cancel was always intended to be &quot;just&quot; an exception that
</I>&gt;<i> happened to be thrown from another thread. But then, nothing is ever
</I>&gt;<i> that simple; the asynchronous nature required controls like
</I>&gt;<i> cancelability type and state. 
</I>
&quot;Asynchronous nature?&quot;

I haven't even been considering asynchronous cancellation as it's
completely untenable to write anything but the most restricted code
that could work in the face of async cancellation.

&gt;<i> C++ exceptions are synchronous and non-interrupting. (The latter a
</I>&gt;<i> consequence of the former, really.)  One of the main advantages of
</I>&gt;<i> cancellation is that it can break through an extended blocking
</I>&gt;<i> operation; 
</I>
If you make all blocking operations cancellation points you can do
that anyway.  No?

&gt;<i> but that's unavoidably an extra condition over &quot;exception-safety&quot;.
</I>&gt;<i> Cancel-safe has to mean something more unless we drop
</I>&gt;<i> interruptibility. If we drop it, then cancel-safety is just
</I>&gt;<i> exception-safety but loses much of its value in controlling
</I>&gt;<i> application responsiveness.
</I>
You lost me.  I think async cancel safety should be thought of as a
separate level of design.

&gt;<i> In any case, though, I wasn't suggesting that you need to convince
</I>&gt;<i> me.  I'm saying there are diverse and strongly held positions that
</I>&gt;<i> somehow need to be unified in order to get consensus on any
</I>&gt;<i> proposal. I think that I'm the least of your worries. ;-)
</I>
Not that you have any obligation to do so, but it might be easier if
you would recognize the weight your opinion carries.  That might mean
learning enough about C++ to form a definite opinion.  That's, at
least, what I've tried to do with threading.

&gt;&gt;&gt;<i> Someone needs to propose and champion &quot;the great exception
</I>&gt;&gt;&gt;<i> compromise&quot;; but if that's to be me I don't yet have the faintest
</I>&gt;&gt;&gt;<i> germ of a notion what it might be. So I sure hope it's going to be
</I>&gt;&gt;&gt;<i> someone else. ;-)
</I>&gt;&gt;&gt;<i>     
</I>&gt;&gt;<i> If &quot;finalized cancellation exceptions result in a new throw at the
</I>&gt;&gt;<i> next cancellation point&quot; isn't enough of a compromise, it isn't going
</I>&gt;&gt;<i> to be me either, because I'm out of new ideas.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Okay, how about this one: we count the number of times the
</I>&gt;&gt;<i> cancellation is discarded.  The cancelling thread can specify the
</I>&gt;&gt;<i> number of discards to tolerate, where the default is infinite.  After
</I>&gt;&gt;<i> that, at the next cancellation point all pthread cancellation handlers
</I>&gt;&gt;<i> (but not dtors or catch blocks) are run and the thread is terminated.
</I>&gt;&gt;<i> Heck, at that point I don't care what happens; you're gambling anyway.
</I>&gt;&gt;<i> Run all the dtors and catch blocks for all I care.
</I>&gt;&gt;<i>   
</I>&gt;<i> I do NOT favor any model where &quot;dtor/catch&quot; and &quot;cancellation handler&quot; 
</I>&gt;<i> don't mean the same thing.
</I>
Like I said, I don't care at that point.  A forced cancellation is a
big gamble.  If &quot;you&quot; want to roll the dice, it's your funeral.

&gt;<i> I don't think the count is tenable either because although it always 
</I>&gt;<i> feels tempting to add a control dial, it doesn't solve any actual 
</I>&gt;<i> problem if there's nobody who can know to what value the dial should be 
</I>&gt;<i> set. 
</I>
Which is why I backed off to the simpler model below.

&gt;<i> If &quot;canceled&quot; state persists when the exception is discarded, then 
</I>&gt;<i> cancel is something different from just &quot;an exception&quot;; 
</I>
It already was something different.  The state needed to be stored
somewhere until the next cancellation point.  This just says that the
state persists until otherwise specified.

&gt;<i> which is too bad, but perhaps inevitable. You can't just catch it
</I>&gt;<i> and continue -- you need to somehow also reset that state to recover
</I>&gt;<i> your workgroup thread that's serially running RPC requests (or
</I>&gt;<i> Python code, whatever). 
</I>
We could do something awful, like have catch-cancellation-by-value
cause the state to be reset, while catch(...) and
catch-cancellation-by-reference don't.  That would preserve the
convenience, at least.

&gt;<i> A lot of people have suggested various ways of making cancel-pending
</I>&gt;<i> persist after the exception is launched; that's not necessarily
</I>&gt;<i> &quot;wrong&quot;, but it isn't &quot;simple&quot; either 
</I>&gt;<i> and somehow it doesn't feel
</I>&gt;<i> right to me.
</I>
It's simpler, by most measures I can think of, than resetting the
state upon throwing.

&gt;&gt;<i> A simpler approach might be to have two kinds of exception: &quot;forced&quot;
</I>&gt;&gt;<i> and finalizable.  At least then we can say that exception-safe code
</I>&gt;&gt;<i> implies finalizable cancellation safety.  Then &quot;forced&quot; synchronous
</I>&gt;&gt;<i> cancellation can do whatever people desire.  I personally think it
</I>&gt;&gt;<i> will become a useless appendage sort of like C++ exception
</I>&gt;&gt;<i> specifications, but at least evolution will take care of it.  And if
</I>&gt;&gt;<i> I'm wrong, evolution will wilt my finalizable cancellations.
</I>&gt;&gt;<i>   
</I>&gt;<i> Is this the &quot;unwind&quot; vs &quot;exception&quot; idea? (Where &quot;unwind&quot; is like a new 
</I>&gt;<i> sort of 'throw' that triggers dtors but can't be caught/finalized.) Or 
</I>&gt;<i> something different...?
</I>
No, I wasn't suggesting anything that couldn't be caught.  I was just
suggesting an exception that couldn't be stopped.  It could throw
itself in its dtor (not that I'm advocating it, but it might satisfy
the &quot;other side&quot;), for example.

In fact, a general mechanism like:

   cancel( thread_id, exception_object );

is possible, where &quot;cancel&quot; really means throw a copy of the given
exception object when the specified thread reaches the next
cancellation point.

We could call it 

   throw_synchronously( thread_id, exception_object );
   
instead, if &quot;cancel&quot; really means forced execution to too many people.

-- 
Dave Abrahams
Boost Consulting
www.boost-consulting.com

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000536.html">[c++-pthreads]  Re: FW: RE: Re: I'm Lost
</A></li>
	<LI>Next message: <A HREF="000538.html">[c++-pthreads]  Re: FW: RE: Re: I'm Lost
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#537">[ date ]</a>
              <a href="thread.html#537">[ thread ]</a>
              <a href="subject.html#537">[ subject ]</a>
              <a href="author.html#537">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">More information about the c++-pthreads
mailing list</a><br>
</body></html>
