<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [c++-pthreads]  Re: FW: RE: Re: I'm Lost
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20%5Bc%2B%2B-pthreads%5D%20%20Re%3A%20FW%3A%20RE%3A%20Re%3A%20I%27m%20Lost&In-Reply-To=%3C52CA6BC0D0E9EE4E93208DB39A3218FE01698F4B%40EXCHANGE.gp.cv.commvault.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000549.html">
   <LINK REL="Next"  HREF="000558.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[c++-pthreads]  Re: FW: RE: Re: I'm Lost</H1>
    <B>George Shimanovich</B> 
    <A HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20%5Bc%2B%2B-pthreads%5D%20%20Re%3A%20FW%3A%20RE%3A%20Re%3A%20I%27m%20Lost&In-Reply-To=%3C52CA6BC0D0E9EE4E93208DB39A3218FE01698F4B%40EXCHANGE.gp.cv.commvault.com%3E"
       TITLE="[c++-pthreads]  Re: FW: RE: Re: I'm Lost">gshiman at commvault.com
       </A><BR>
    <I>Wed Mar  8 17:08:33 UTC 2006</I>
    <P><UL>
        <LI>Previous message: <A HREF="000549.html">[c++-pthreads]  Re: FW: RE: Re: I'm Lost
</A></li>
        <LI>Next message: <A HREF="000558.html">[c++-pthreads]  Re: FW: RE: Re: I'm Lost
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#548">[ date ]</a>
              <a href="thread.html#548">[ thread ]</a>
              <a href="subject.html#548">[ subject ]</a>
              <a href="author.html#548">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>&gt;<i>I don't think we should support unstoppable exceptions at all.
</I>Silently
&gt;<i>rethrowing at the end of a catch handler breaks too many important
</I>&gt;<i>invariants.
</I>
For example, it is not compatible with thread pool implementations that
try to reuse its threads regardless of how thread callback completes,
normally or via thread cancellation. Note that since cancellation
exception can only be caught via catch(...) there is no way to
distinguish it from any system, non-C++ exception and thus decide to
rethrow.

George Shimanovich

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000549.html">[c++-pthreads]  Re: FW: RE: Re: I'm Lost
</A></li>
	<LI>Next message: <A HREF="000558.html">[c++-pthreads]  Re: FW: RE: Re: I'm Lost
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#548">[ date ]</a>
              <a href="thread.html#548">[ thread ]</a>
              <a href="subject.html#548">[ subject ]</a>
              <a href="author.html#548">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">More information about the c++-pthreads
mailing list</a><br>
</body></html>
